verb =  [
"Accelerating",
"Achieving",
"Addressing",
"Advancing",
"Bridging",
"Bringing",
"Building",
"Boosting",
"Capacitating",
"Catalyzing",
"Championing",
"Complementing",
"De-risking",
"Developing",
"Diversifying",
"Empowering",
"Encouraging",
"Engaging",
"Engendering",
"Enhancing",
"Establishing",
"Expanding",
"Exploring",
"Evaluating",
"Facilitating",
"Financing",
"Focusing",
"Fostering",
"Gender-Sensitizing",
"Greening",
"Growing",
"Harmonizing",
"Implementing",
"Improving",
"Incentivizing",
"Institutionalizing",
"Investing in",
"Laying the Foundations of",
"Leveling the Playing Field for",
"Leveraging",
"Liberalizing",
"Linking",
"Mainstreaming",
"Making",
"Maximizing",
"Mobilizing",
"Modernizing",
"Monitoring",
"Operationalizing",
"Partnering",
"Prioritizing",
"Producing",
"Promoting",
"Promoting Innovation on",
"Providing",
"Raising",
"Realizing",
"Rebuilding",
"Reforming",
"Repositioning",
"Restructuring",
"Rethinking",
"Revitalizing",
"Scaling-Up",
"Steering",
"Streamlining",
"Strengthening",
"Supporting",
"Sustaining",
"Tracking",
"Transforming",
"Utilizing",
"Workshop on",
"Writeshop on"
]

modifier =  [
"Agribusiness",
"Aid",
"Appropriate",
"Blockchain",
"Carbon Sequestration",
"Climate",
"Coastal",
"Community-Based",
"Community-Driven",
"Core",
"Cost-Effective",
"Collaborative",
"Consultative",
"Country-Led",
"Crop",
"Cross-Regional",
"Cross-Cutting",
"Digital",
"Disaster Risk Reduction",
"E-Government",
"Economic",
"Ecotourism",
"Effective",
"Efficient",
"Emerging",
"Empowered",
"Energy Generation",
"Environmental",
"Equitable",
"Evidence-Based",
"Fiscal",
"Food",
"Forest",
"Fisheries",
"Gender-Sensitive",
"Global",
"Grassroots-Oriented",
"Green Jobs",
"ICT4D",
"Inclusive",
"Indigenous",
"Industrial",
"Inequality-Reducing",
"Innovative",
"Institutional",
"Integrated",
"Inter-Agency",
"Intergovernmental",
"Irrigation",
"Job",
"Key",
"Labor",
"Local",
"Market-Oriented",
"Microfinance",
"Multi-Sectoral",
"Multpartite",
"National",
"Open Data",
"Participatory",
"Peace and Justice",
"Post-2015",
"Post-Conflict",
"Post-Disaster",
"Primary Health Care",
"Pro-Poor",
"Public",
"Public-Private",
"Regional",
"Regulatory",
"Responsible",
"Safety Net",
"Space Force",
"Strategic",
"Social Protection",
"South-South",
"Sub-National",
"Sustainable",
"Systematic",
"Telecommunication",
"the 2030 Agenda",
"Tourism",
"Transparent",
"Universal Health Coverage",
"Value-Chain",
"Value-for-Money",
"Water"
]

noun =  [
"Adaptation",
"Access",
"Accountability",
"Activities",
"Administration",
"Approaches",
"Assessment",
"Assistance",
"Best Practices",
"Capability",
"Capacity",
"Co-Benefits",
"Collaboration",
"Committments",
"Communication and Outreach",
"Competitiveness",
"Conditional Cash Transfers",
"Consumption and Production",
"Cooperation",
"Development",
"Development Framework",
"Dialogue",
"Diversity",
"Economies",
"Effectiveness",
"Efficiency",
"Enterprise",
"Equality",
"Extension and Research",
"Financing for Development",
"Goals",
"Governance",
"Growth",
"Impact",
"Inclusion",
"Inclusivity",
"Indicators",
"Income-Generation",
"Industries",
"Innovation",
"Institutions",
"Integration",
"Interventions",
"Involvement",
"Knowledge, Skills and Practices",
"Knowledge Management",
"Lending",
"Linkages",
"Liberalization",
"Livelihoods",
"Management",
"Markets",
"Mechanisms",
"Monitoring and Evaluation",
"Opportunities",
"Outcomes",
"Participation",
"Partners",
"Partnerships",
"Performance",
"Planning",
"Plans",
"Platforms",
"Policies",
"Policy Framework",
"Portfolio",
"Poverty Reduction",
"Priorities",
"Privatization",
"Processes",
"Production",
"Programs",
"Progress",
"Prosperity",
"Recovery",
"Reforms",
"Resources",
"Responsiveness",
"Results",
"Hygiene and Sanitation",
"Schemes",
"Security",
"Services",
"Stability",
"Stakeholders",
"Strategies",
"Sustainability",
"Synergies",
"Targets",
"Technical Assistance",
"Technologies",
"Transparency"
]

object = [
"for Direct Target Beneficiaries",
"for Indigenous People",
"for Fisherfolks",
"for Local Policymakers and Practitioners",
"for Poor People",
"for Remote Populations",
"for Small-Holder Farmers",
"for State-Owned Enterprises",
"for the Global Commons",
"for the Poorest of the Poor",
"for the World Economy",
"in a Volatile World",
"in Arid Regions",
"in Biodiversity Hotspots",
"in Civil Society Organizations",
"in Client Countries",
"in Developing Countries",
"in Emerging Economies",
"in Emerging Markets",
"in Far-Flung Communities",
"in Fishing Communities",
"in Fragile and Failed States",
"in Frontier Markets",
"in Growing Economies",
"in Highly-Urbanized Areas",
"in Indigenous Communities",
"in Industrializing Nations",
"in Land-Locked Countries",
"in Least Developed Countries",
"in Less Developed Countries",
"in Less Economically Developed Countries",
"in LMICs",
"in Low- and Middle-Income Countries",
"in Low-Income Households",
"in Low-Lying Communities",
"in DONGOs, MANGOs, and TANGOs",
"in Marginalized Communities",
"in Member-States",
"in Middle-Income Countries",
"in MNCs, INGOs, and BINGOs",
"in Natural Habitats",
"in Newly-Industrialized Countries",
"in Off-Grid Villages",
"in Pastoral Communities",
"in Poor Nations",
"in Protected Areas",
"in Remote Communities",
"in Remote Villages",
"in Rural Communes ",
"in Rurban Areas",
"in Semi-Arid Regions",
"in Small Island Developing States",
"in Sustainable Cities",
"in the Business Sector",
"in the Developing World",
"in the Field",
"in the Global South",
"in the Last Frontier of the World",
"in the Local Government",
"in the Poorest Countries",
"in the Private Sector",
"in the Regional and Global Arena",
"in Transboundary Trade Corridors",
"in Transnational Borders",
"in Tropical Forests",
"in Underdeveloped Countries",
"in Upland Areas",
"in Vulnerable Nations",
"in Vulnerable Populations",
"to Downstream Actors",
]


function newTitle() {
  console.log ("== newTitle ==")
  let randVerb = verb[Math.floor(Math.random() * verb.length)];
  let randModifier = modifier[Math.floor(Math.random() * modifier.length)];
  let randNoun = noun[Math.floor(Math.random() * noun.length)];
  let randObject = object[Math.floor(Math.random() * object.length)];

  document.getElementById("string1").innerHTML = randVerb;
  document.getElementById("string2").innerHTML = randModifier;
  document.getElementById("string3").innerHTML = randNoun;
  document.getElementById("string4").innerHTML = randObject;
}
